// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type IsAny<T> = 0 extends 1 & T ? true : false
type InjectionType<A extends Plugin> = IsAny<A> extends true ? unknown : A extends Plugin<infer T> ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.2.0_encoding@0.1.13_ioredis@5.4.1_magicast@0_s6eobon7dodctnb23fvjqyitha/node_modules/nuxt/dist/app/plugins/navigation-repaint.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.2.0_encoding@0.1.13_ioredis@5.4.1_magicast@0_s6eobon7dodctnb23fvjqyitha/node_modules/nuxt/dist/app/plugins/check-outdated-build.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.2.0_encoding@0.1.13_ioredis@5.4.1_magicast@0_s6eobon7dodctnb23fvjqyitha/node_modules/nuxt/dist/app/plugins/revive-payload.server").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.2.0_encoding@0.1.13_ioredis@5.4.1_magicast@0_s6eobon7dodctnb23fvjqyitha/node_modules/nuxt/dist/app/plugins/revive-payload.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.2.0_encoding@0.1.13_ioredis@5.4.1_magicast@0_s6eobon7dodctnb23fvjqyitha/node_modules/nuxt/dist/app/plugins/chunk-reload.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.5.3_magicast@0.3.4_rollup@4.20.0_vue@3.4.38/node_modules/@pinia/nuxt/dist/runtime/plugin.vue3").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.2.0_encoding@0.1.13_ioredis@5.4.1_magicast@0_s6eobon7dodctnb23fvjqyitha/node_modules/nuxt/dist/head/runtime/plugins/unhead").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.2.0_encoding@0.1.13_ioredis@5.4.1_magicast@0_s6eobon7dodctnb23fvjqyitha/node_modules/nuxt/dist/pages/runtime/plugins/router").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.2.0_encoding@0.1.13_ioredis@5.4.1_magicast@0_s6eobon7dodctnb23fvjqyitha/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.2.0_encoding@0.1.13_ioredis@5.4.1_magicast@0_s6eobon7dodctnb23fvjqyitha/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@storyblok+nuxt@6.0.10/node_modules/@storyblok/nuxt/dist/runtime/plugin").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/vuetify-nuxt-module@0.17.1_magicast@0.3.4_rollup@4.20.0_vite@5.4.0_@types+node@22.2.0_sass@1._2fpasihdolf5it3pbhxcgupc7a/node_modules/vuetify-nuxt-module/dist/runtime/plugins/vuetify-date").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/vuetify-nuxt-module@0.17.1_magicast@0.3.4_rollup@4.20.0_vite@5.4.0_@types+node@22.2.0_sass@1._2fpasihdolf5it3pbhxcgupc7a/node_modules/vuetify-nuxt-module/dist/runtime/plugins/vuetify-icons").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/vuetify-nuxt-module@0.17.1_magicast@0.3.4_rollup@4.20.0_vite@5.4.0_@types+node@22.2.0_sass@1._2fpasihdolf5it3pbhxcgupc7a/node_modules/vuetify-nuxt-module/dist/runtime/plugins/vuetify-client-hints.server").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/vuetify-nuxt-module@0.17.1_magicast@0.3.4_rollup@4.20.0_vite@5.4.0_@types+node@22.2.0_sass@1._2fpasihdolf5it3pbhxcgupc7a/node_modules/vuetify-nuxt-module/dist/runtime/plugins/vuetify-client-hints.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+apollo@file+..+@hc+apollo_magicast@0.3.4_rollup@4.20.0_vue@3.4.38/node_modules/@nuxtjs/apollo/dist/runtime/plugin").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@1.3.9_rollup@4.20.0_vite@5.4.0_@types+node@22.2.0_sass@1.77.8_terser@5.31.5_/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@1.3.9_rollup@4.20.0_vite@5.4.0_@types+node@22.2.0_sass@1.77.8_terser@5.31.5_/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.2.0_encoding@0.1.13_ioredis@5.4.1_magicast@0_s6eobon7dodctnb23fvjqyitha/node_modules/nuxt/dist/app/plugins/dev-server-logs").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.2.0_encoding@0.1.13_ioredis@5.4.1_magicast@0_s6eobon7dodctnb23fvjqyitha/node_modules/nuxt/dist/app/plugins/check-if-layout-used").default> &
  InjectionType<typeof import("../../src/plugins/vuetify").default>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'vuetify:date:plugin' | 'vuetify:icons:plugin' | 'vuetify:client-hints:client:plugin' | 'nuxt:head' | 'nuxt:router' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'pinia' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | 'nuxt:checkIfLayoutUsed' | 'vuetify:client-hints:server:plugin' | 'vuetify:nuxt:server:plugin' | 'vuetify:nuxt:client:plugin'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
